name: SendMessage
main: qreardedwastaken\SendMessage\main
api: 4.0.0
version: 1.0.0
author: qreardedwastaken

commands:
  sendmessage:
    description: "Sends a message."
    permission: default.use
  
permissions:
  default.use:
    description: "Does not require authorization."
    default: true
